### ISSUE TITLE
Document key usage.

### ISSUE THREAD

**Issue by andor44** [GildedHonour/frank_jwt#18]
I had to dig into the sources to find out that the keys everywhere are assumed to be supplied PEM encoded. This is not documented anywhere so at first I was just guessing what the library was expecting. Also, in my case I have RSA pubkeys where I know N and E, and I don't want to have to convert this to PEM only to end up getting it converted back into its original form. The library should consider offering other encodings, since the underlying OpenSSL allows it anyway.

**Comment by andor44** [comment]
The singular `decode`/`encode` pair makes for a very clean API, but also a very inflexible one as seen here. How about having individual functions for the different key types (symmetric key, RSA, EC) that take their respective, underlying key type (byte blob, `openssl::rsa::Rsa` and `openssl::ec::EcKey` respectively), and have `decode` dispatch to those? This keeps the simple interface of today, but if you already have a more specific key type on hand you can use that. Or perhaps another approach would be having a wrapper enum for the different key types, and `ToKey::to_key` returning one of them.

**Comment by GildedHonour** [comment]
Ok, will look into that
