### ISSUE TITLE
Misleading ReadMe

### ISSUE THREAD

**Issue by seunlanlege** [GildedHonour/frank_jwt#22]
I've looked through the source code, and while the readme claims that it checks all *registered jwt claims*

There's nothing in the code that actually does that. the readme should be updated with this, so as not to confuse users

 - [x]  HS256
 - [x]     HS384
 - [x]     HS512
 - [x]    RS256
 - [x]    RS384
 - [x]     RS512
 - [x]    ES256
 - [x]     ES384
 - [x]     ES512
 - [x]    Sign
 - [x]     Verify
 - [ ]     iss (issuer) check
 - [ ]     sub (subject) check
 - [ ]     aud (audience) check
 - [ ]     exp (expiration time) check
 - [ ]     nbf (not before time) check
 - [ ]    iat (issued at) check
 - [ ]     jti (JWT id) check

**Comment by GildedHonour** [comment]
You're right, I'll implement that.

**Comment by jbboehr** [comment]
It looks like this is a feature I kind of need (at least the `exp` part) - is there an estimate on how long until it might be ready, or perhaps should I take a stab at implementing it?

**Comment by ivanovaleksey** [comment]
@GildedHonour hello, what is the current status for that?
I wouldn't mind to contribute though I would need some guidance.
I am new to JWT, for now I only need to validate a token with `sub` claim.
Do I need to implement [this](https://github.com/GildedHonour/frank_jwt/blob/master/src/lib.rs#L277) method for that?

**Comment by GildedHonour** [comment]
I'm working on that

**Comment by amouat** [comment]
I think it would be best to update the README to make clear this work is in progress. At the moment you have people using the crate but it's not doing important security checks that it says it is doing.

Thanks for all your work on this crate - I don't mean to give you a hard time.
