### ISSUE TITLE
Compiler errors due to old 0.9 version of `openssl` crate.

### ISSUE THREAD

**Issue by freiguy1** [GildedHonour/frank_jwt#45]
My system has OpenSSL 1.1.1, and openssl crate 0.9 doesn't work with it. Check out the related issue here:

https://github.com/sfackler/rust-openssl/issues/987

That issue has been linked to several other issues like this one for crates with the same issue as frank_jwt.

Thanks!

**Comment by mbelop** [comment]
While openssl-rust crate dependency has been bumped to 0.10 in b5dc47ed608448c7c6a02f97e7f2140548220336, crates.io index wasn't updated, so cargo thinks there were no updates to this crate. Perhaps a new release is in order?

**Comment by koala-kalda** [comment]
Just submitted a PR to resolve this. #46

**Comment by Gisleburt** [comment]
I suspect it's not reflected the change because its a `< 1.0` release, therefore Cargo can not assume it's BC safe.

For those looking for a work around, you can use @koala-kalda's branch temporarily by changing you Cargo.lock to use his commit:
```toml
frank_jwt = { git = "https://github.com/koala-kalda/frank_jwt", rev = "af4f3480fa26f628519712df719470feb7654896" }
```

**Comment by apiraino** [comment]
I was blocked, too, with my Rocket project but the workaround helped.
 
Looking forward to seeing #46 merged, thanks! :+1:

**Comment by GildedHonour** [comment]
openssl = "0.10.15"
