### ISSUE TITLE
The function "encode" for the RS algorithms

### ISSUE THREAD

**Issue by GildedHonour** [GildedHonour/frank_jwt#5]
At the moment for the RS algorithms the function encode expects a path to a private pem file rather than a structure representing a private pem file itself. Should it be changed, leave your comment.

**Comment by Richterrettich** [comment]
I would like to see a version of the encode/decode function that can handle an in-memory data structure.
I can also help implementing this. Are you open for breaking changes or do you want a different encode/decode function for  this?

**Comment by GildedHonour** [comment]
@Richterrettich 
>I would like to see a version of the encode/decode function that can handle an in-memory data structure.

will you elaborate?

**Comment by hammett** [comment]
Same here. We're using cognito so different keys per user pool, and per token type. An in mem representation would be excellent. Also, using the modulus + e directly, which would translate to a call to https://docs.rs/openssl/0.10.5/openssl/rsa/struct.Rsa.html#method.from_public_components instead.

**Comment by GildedHonour** [comment]
Ok, will look into that
