### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by Pierozi** [GildedHonour/frank_jwt#55]
Hello there,

Thanks for this great library!
I can see that many change has not yet been release on cargo, like the `impl ToKey for &str`

**Comment by coltfred** [comment]
We also would like to consume a new release, but really need #53 merged first (which we've tested in our code and it works).

**Comment by GildedHonour** [comment]
done

**Comment by GildedHonour** [comment]
I'll update it on crates later

**Comment by kellytk** [comment]
@GildedHonour Do you have an ETA of pushing the new release to crates.io?

**Comment by GildedHonour** [comment]
@kellytk I think in September or October, if I have time.
Or maybe I've already updated it? :)
