### ISSUE TITLE
ECDSA nistp256 from HEX

### ISSUE THREAD

**Issue by Pierozi** [GildedHonour/frank_jwt#56]
Hi, I'm struggling to encode using a private key in hexadecimal format with curve `secp256r1`.

As far my understanding, I have to convert my hex key into PEM to be able to use it but search on OpenSSL or others libraries for hours, cannot find the proper way to do that.

```rust
let HEX_PRIVATE_KEY = "0eab97f8cc6bdc165f51a1a1c08eb91f08903ccb9da599d7f7923ac63badc531";

let group = openssl::ec::EcGroup::from_curve_name(openssl::nid::Nid::ECDSA_WITH_SHA256).unwrap();
let point = openssl::ec::EcPoint::new(&group).unwrap();
let private_number = openssl::bn::BigNum::from_hex_str(&HEX_PRIVATE_KEY).unwrap();
let eckey = openssl::ec::EcKey::from_private_components(
    &group,
    &private_number,
    &point
).unwrap();
let private_key = eckey.private_key_to_pem().unwrap();

let jwt_token = match frank_jwt::encode(header, &private_key, &payload, frank_jwt::Algorithm::ES256) {
    Ok(token) => token,
    Err(error) => {
        panic!("There was a problem during JWT ENCODE: {:?}", error);
    },
};

```

This is how it should be done?

**Comment by Pierozi** [comment]
Solve it, the public key was missing.

```rust
let private_key_hex = "a3ed0dd27cbfa62e13e340fb3dbb86895b99d5fd330a80e799baffcb1d29c17a";
let private_number: BigNum = match BigNum::from_hex_str(private_key_hex) {
    Ok(bn) => bn,
    Err(error) => panic!("Error during parsing private key in hex, please check your configuration: {:?}", error),
};

let group: EcGroup = EcGroup::from_curve_name(openssl::nid::Nid::X9_62_PRIME256V1).unwrap();
let mut context: BigNumContext = BigNumContext::new().unwrap();

let mut public_point = EcPoint::new(&group).unwrap();
match public_point.mul_generator(
    &group,
    &private_number,
    &mut context
) {
    Ok(_) => (),
    Err(error) => panic!("Error during public key generation from private key. key must be ECDSA nist256 format: {:?}", error),
}

let eckey: EcKey<Private> = match EcKey::from_private_components(
    &group,
    &private_number,
    &public_point
) {
    Ok(key) => key,
    Err(error) => panic!("Error pub/pvt key construction: {:?}", error),
};

return match eckey.private_key_to_pem() {
    Ok(pem) => pem,
    Err(error) => panic!("Error during PEM conversion: {:?}", error),
};

```

**Comment by GildedHonour** [comment]
Thx

El 3 de junio de 2019 18:08:11 GMT-03:00, Pierre Tomasina <notifications@github.com> escribió:
>Solve it, the public key was missing.
>
>```rust
>let private_key_hex =
>"a3ed0dd27cbfa62e13e340fb3dbb86895b99d5fd330a80e799baffcb1d29c17a";
>let private_number: BigNum = match
>BigNum::from_hex_str(private_key_hex) {
>    Ok(bn) => bn,
>Err(error) => panic!("Error during parsing private key in hex, please
>check your configuration: {:?}", error),
>};
>
>let group: EcGroup =
>EcGroup::from_curve_name(openssl::nid::Nid::X9_62_PRIME256V1).unwrap();
>let mut context: BigNumContext = BigNumContext::new().unwrap();
>
>let mut public_point = EcPoint::new(&group).unwrap();
>match public_point.mul_generator(
>    &group,
>    &private_number,
>    &mut context
>) {
>    Ok(_) => (),
>Err(error) => panic!("Error during public key generation from private
>key. key must be ECDSA nist256 format: {:?}", error),
>}
>
>let eckey: EcKey<Private> = match EcKey::from_private_components(
>    &group,
>    &private_number,
>    &public_point
>) {
>    Ok(key) => key,
>   Err(error) => panic!("Error pub/pvt key construction: {:?}", error),
>};
>
>return match eckey.private_key_to_pem() {
>    Ok(pem) => pem,
>    Err(error) => panic!("Error during PEM conversion: {:?}", error),
>};
>
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GildedHonour/frank_jwt/issues/56#issuecomment-498427221

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.
