### ISSUE TITLE
Feature request: decode without verifying the signature

### ISSUE THREAD

**Issue by promethe42** [GildedHonour/frank_jwt#58]
Hi,

I need to decode the JWT to get the content, and in some context I don't care about whether it's properly signed or not. But `decode_segments` is private.

Could you please make `decode_segments` public?

Regards,

**Comment by GildedHonour** [comment]
Probably not, because it's only you and perphaps a handful of people who need that.

**Comment by GildedHonour** [comment]
And the less is exposed to the client, the better.

**Comment by promethe42** [comment]
> it's only you and perphaps a handful of people who need that

AFAIK that is not correct.
Being able to decode a JWT without the key and without verifying the signature is an actual feature widely supported by other implementations.

Here is are examples:

* [NodeJS implementation](https://www.npmjs.com/package/jsonwebtoken#jwtdecodetoken--options)
* [Python implementation](https://pyjwt.readthedocs.io/en/latest/usage.html#reading-the-claimset-without-validation)
* [Java implementation](https://github.com/auth0/java-jwt#decode-a-token)
* [C implementation](http://benmcollins.github.io/libjwt/group__jwt__new.html#ga4d498ffdcf1c95d67b81c224e2a447e5)

It's so commonly supported that the JWT "debugger" available on the front page of [the official JWT website](https://jwt.io/) does it to.

**Comment by GildedHonour** [comment]
The statement was "who needs it", not "where it's implemented or supported".

**Comment by promethe42** [comment]
The statement was "only you need it". My answer is "no it's such a classic
use case it's on the front page of the official website".

**Comment by GildedHonour** [comment]
No.

>because it's only you and perphaps a handful of people who need that.

**Comment by GildedHonour** [comment]
When there're more people who need it, I'll make it public.

**Comment by FibreFoX** [comment]
Just a stupid idea: how about exposing that function as some `unsafe` version (even the code isn't unsafe)? This makes sure that the people using it are not falling into the "untrusted"-deception (like mentioned here https://connect2id.com/products/nimbus-jose-jwt/vulnerabilities), but still being able to use that part.

**Comment by promethe42** [comment]
> Just a stupid idea: how about exposing that function as some unsafe version

It's an unproper use of `unsafe`.
It would be better to enable it through an optional feature flag.

**Comment by GildedHonour** [comment]
Noted
