### ISSUE TITLE
Release 3.1.2 with bugfixes?

### ISSUE THREAD

**Issue by coltfred** [GildedHonour/frank_jwt#61]
Thank you so much for your hard work on this library. We've been running into issues with `panicked at 'assertion failed: start <= end', src/liballoc/vec.rs:1269:9` when using ES256 JWTs.

This has been fixed (as far as I can tell) by the work done in #60.

Could we please get a published release so we don't have to depend on the master git hash?

**Comment by GildedHonour** [comment]
@coltfred uploaded
