### ISSUE TITLE
Follow semver

### ISSUE THREAD

**Issue by TatriX** [GildedHonour/frank_jwt#62]
According to [semver](https://semver.org/) one should bump *major* version when introducing incompatible API changes.
#59 introduced breaking changes and thus broke others [code](https://github.com/TatriX/realworld-rust-rocket/pull/20).
Thanks!

**Comment by GildedHonour** [comment]
I don't follow the recommendations of semver.

**Comment by GildedHonour** [comment]
Thanks for what?

**Comment by TatriX** [comment]
This is unfortunate, because that's what people expect: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

It would be nice if you could mention this fact in the readme, so users of the library could pin dependency to a specific version.

Thanks for you work on the useful package.

**Comment by GildedHonour** [comment]
Useful package? Ahhhaaa. Nothing useful in it.
 
Don't worry about other users. No user has ever complained about bumping the major version.
