### ISSUE TITLE
Нужен NFT Программист 

### ISSUE THREAD

**Issue by Zetor999** [GildedHonour/frank_jwt#66]
ДД
Создаем коллекцию NFT
Ищем разработчика для создания сайта для минта (смарт контракт) и все необходимое для успешного выпуска коллекции в OpenSea на ETH

**Comment by Zetor999** [comment]
напиши в телегу alex_wildup

**Comment by GildedHonour** [comment]
Странный человек

"Мне нужны ваши услуги. Побегайте за мной"

**Comment by Zetor999** [comment]
Я жетонной написал данные телеграм
+79370922000 - телефон

**Comment by GildedHonour** [comment]
Да мне без разницы. Если вы ищите - узнавайте как связаться с разработчиком, и пишите ему.
