### ISSUE TITLE
Bug: JWT with unix timestamps with a float are detected as expired

### ISSUE THREAD

**Issue by thacoon** [GildedHonour/frank_jwt#67]
Unix timestamps can also exists as floating points, for example `1700689265.2850804` is a valid unix timestamp. 

Currently the `verify_expiration` function would fail and any jwt that has such a unix timestamp would be marked as expired, although they are not.

**Comment by thacoon** [comment]
I created a small pull request for it #68

**Comment by GildedHonour** [comment]
done
