### ISSUE TITLE
Clarify how the RSA keys were generated

### ISSUE THREAD

**Issue by MoreAxes** [GildedHonour/frank_jwt#9]
I can't seem to get OpenSSL to generate a key-cert pair that won't cause a panic on decode() with an error message like 

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: OpenSslErrors([UnknownError { library: "PEM routines", function: "PEM_read_bio", reason: "no start line" }])', ../src/libcore\result.rs:837
```

However, the keys in the `test` directory work fine. Could you please share the exact invocation of OpenSSL you used to generate them, or if you didn't use OpenSSL, describe how you did it?

**Comment by GildedHonour** [comment]
I don't remember. I'm rewritting it to a new version of openssl.
